version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "5000:80"

  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: report
        MYSQL_ROOT_PASSWORD: 12345Aa.
    ports:
      - 5001:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
