version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "5000:80"

  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: larReport
        MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 5101:3306
