version: '3'

services:
  nginx:
    image: nginx:latest
    volumes: 
      - .:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "5000:80"

  app:
    image: php:8.2-fpm
    build: 
      context: .
      dockerfile: ./docker/Dockerfile