version: "3"
services:
  php:
    image: php:8.2-fpm # Use the PHP 8.2 FPM (FastCGI Process Manager) image
    build:
      context: . # Build the image using the current directory as the build context
      dockerfile: ./Dockerfile # Use the specified Dockerfile for building the image
    volumes:
      - .:/app
    ports:
      - "8000:8000"
